### ISSUE TITLE
resources for API

### ISSUE THREAD

**Issue by pixelass** [WeeJeWel/node-webos#2]
Hi. I just stumbled upon this project through your issue on msloth's repo. I was just about to rewrite the entire module since I am building a react powered client on top of `lgtv` and want a reliable source.

I had the same issue with the youtube video not starting (while opening the browser with an URL works) and I couldn't really find anything about it online.

Do you know any good resources?  
Which resources are you using?  

If I feel comfortable with your implementation I'm happy to contribute.  I'll most probably do a rewrite in ES2015/esnext tough.

In any case I'll be happy to keep you posted on the client and/or module I am making.

Here's a gif of the first prototype:

![lgremote](https://cloud.githubusercontent.com/assets/1148334/13373707/509b1656-dd6f-11e5-8844-627cee2aff63.gif)

**Comment by WeeJeWel** [comment]
Looks very nice! I haven't gotten around to YouTube yet.

My main reference has been https://github.com/msloth/lgtv.js, but that repository is inactive since a month or so.

**Comment by pixelass** [comment]
I am also using everything I could find inside the code source but it seems limited.

Here's something that I just found: https://mym.hackpad.com/ep/pad/static/rLlshKkzdNj  
It has a list of all or a lot of URL endpoints.

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.
